mysite/myapp/urls.py
from django.contrib import admin
from django.urls import path
from myapp import views

app_name = 'myapp'  # namespacing

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('index/', views.index, name='index'),
    path('', views.index, name='index'),
    path('book/<int:book_id>/', views.detail, name='detail'),
    path('add/', views.add_book, name='add_book'),
    path('update/<int:id>/', views.update, name='update'),
    path('delete/<int:id>/', views.delete, name='delete'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from myapp import views
from . import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('myapp.urls')),  # include URL handlers from another url file

                  # path('index/', views.index, name='index'),
                  # path('book/<int:book_id>/', views.detail,name='detail'),
              ] + static(settings.MEDIA_URL,
                         document_root=settings.MEDIA_ROOT)  # create url path to access image upload folder

mysite/myapp/models.py
from django.db import models


# Create your models here.
class Book(models.Model):

    # To view the record name entered in specific object while using Django ORM shell
    def __str__(self):
        return self.name

    name = models.CharField(max_length=100)  # book name
    description = models.CharField(max_length=300)  # book description
    price = models.IntegerField()
    bookimage = models.ImageField(default='default.jpg', upload_to='book_images/')  # store book cover image

mysite/myapp/forms.py
# this function class inherits the book model fields to create and reuse and render a single form template for
# creating forms for editing data or adding data in webpages.

from django import forms
from .models import Book


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['name', 'description', 'price', 'bookimage']

mysite/myapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Book
from .forms import BookForm


# Create your views here.
def index(request):
    book_list = Book.objects.all()
    context = {
        'book_list': book_list
    }
    return render(request, 'myapp/index.html', context)


def detail(request, book_id):
    book = Book.objects.get(id=book_id)
    return render(request, 'myapp/detail.html', {'book': book})


def add_book(request):
    if request.method == "POST":
        name = request.POST.get('name', )
        description = request.POST.get('description', )
        price = request.POST.get('price', )
        bookimage = request.FILES['bookimage']

        book = Book(name=name, description=description, price=price, bookimage=bookimage)
        book.save()
    return render(request, 'myapp/add_book.html')


def update(request, id):
    book = Book.objects.get(id=id)
    form = BookForm(request.POST or None, request.FILES, instance=book)
    if form.is_valid():
        form.save()
        return redirect('/')

    return render(request, 'myapp/edit.html', {'form': form, 'book': book})


def delete(request, id):
    if request.method == "POST":
        book = Book.objects.get(id=id)
        book.delete()
        return redirect('/')
    return render(request, 'myapp/delete.html')

mysite/myapp/templates/myapp/add_book.html
{% extends 'myapp/base.html' %}

{% block body %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" id="name" placeholder="Enter book name">
    <input type="text" name="description" id="description" placeholder="Enter description of the book">
    <input type="text" name="price" id="price" placeholder="Enter book price">
    <input type="file" name="bookimage" id="bookimage">
    <input type="submit" value="Add Book" class="btn btn-primary">
</form>

{% endblock %}

mysite/myapp/templates/myapp/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'myapp/style.css' %}">
    <title>Document</title>
</head>
<body>
    <nav class="navbar bg-body-tertiary bg-dark border-bottom border-body" data-bs-theme="dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'myapp:index' %}">Online Book Store</a>
      </div>
    </nav>

    {% block body %}
    <!--  web content and code will be loaded here in the base  -->
    {% endblock %}

</body>
</html>

mysite/myapp/templates/myapp/delete.html
{% extends 'myapp/base.html' %}

{% block body %}

<form method="post">
    {% csrf_token %}
    Are you sure you want to delete this book?
    <input type="submit" class="btn btn-warning btn-sm">
</form>

{% endblock %}

mysite/myapp/templates/myapp/detail.html
{% extends 'myapp/base.html' %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{book.bookimage.url}}" width="300" height="500">
        </div>
        <div class="col-md-6">
            <h2>{{book.name}}</h2>

            <h4>{{book.description}}</h4>

            <h6>Cost: ${{book.price}}</h6>

            <a href="{% url 'myapp:update' book.id %}">
                <button class="btn btn-warning">Edit Book</button>
            </a>
            <a href="{% url 'myapp:delete' book.id %}">
                <button class="btn btn-danger">Delete Book</button>
            </a>
        </div>
    </div>
</div>



{% endblock %}

mysite/myapp/templates/myapp/edit.html
{% extends 'myapp/base.html' %}

{% block body %}

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
<!--    The form from the add book form will render here -->
    {{ form.as_p }}
    <input type="submit" value="Add Book" class="btn btn-primary">
</form>

{% endblock %}

mysite/myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}

{% block body %}

<a href="{% url 'myapp:add_book' %}">
    <button class="btn btn-primary btn-sm">Add Book</button>
</a><br><br>



<div class="container">
    <div class="row">
        {%for book in book_list%}
        <div class="col-md-3">
            <div class="card">
                <img class="card-img-top" src="{{book.bookimage.url}}" alt="" width="100" height="300">
                <div class="card-body">
                    <h5 class="card-title">{{book.name}}</h5>
                    <p class="card-text">${{book.price}}</p>
                    <a class="btn btn-info btn-sm" href="{% url 'myapp:detail' book.id %}">View Details</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>


{% endblock %}